theme: jekyll-theme-slate
title: h.lab
description: Empowering hands-on experimentation with and critical reflection on new and emerging computational tools and methods by scholars and students in the humanities
