theme: jekyll-theme-slate
title: h.lab
description: Case Western Reserve University
Timothy Beal, director
Empowering hands-on experimentation with and critical reflection on new and emerging computational tools and methods by scholars and students in the humanities
