theme: jekyll-theme-minimal
logo: <img src="/hlab_logo.png" width="200" height="200" />
title: h.lab
description: empowering students and scholars in the humanities to experiment with and critically reflect on new and emerging computational technologies
