theme: jekyll-theme-minimal
logo: "/assets/img/hlab_logo.png"
title: h.lab
description: empowering students and scholars in the humanities to experiment with and critically reflect on new and emerging computational technologies
