theme: jekyll-theme-slate
title: h.lab
description: empowering students and scholars in the humanities to experiment with and critically reflect on new and emerging computational tools and methods / Case Western Reserve University / Timothy Beal, director
